language: node_js
node_js:
  - 12
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g serverless
  - npm run build
script:
  - serverless deploy  --stage dev # travis config includes AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables